[package]
name = "wasm-script-interpreter"
version = "0.1.0"
authors = ["Nick Carton <nick.carton@protonmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[build]
target = "wasm32-unknown-unknown"

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.81"
bsv-wasm = { path = "../bsv-wasm" }
serde-wasm-bindgen = "0.4.3"
# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[patch.crates-io]
wasm-bindgen = { git = "https://github.com/bsvwasm/wasm-bindgen", branch = "universal-ui64-patch" }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
