name: Test & Publish

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'New Release Version (SemVer)'     
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: [test, node-test]

    steps:
    - uses: actions/checkout@v2
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
        version: 'latest'

    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true

    - uses: katyo/publish-crates@v1
      with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

    - run: sed -i "s/version = "<VERSION_NUMBER>"/version = "${{ github.event.inputs.version }}"/" ./Cargo.toml

    - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

    - name: Publish Node Package
      run: make publish-node

    - name: Publish Web Package
      run: make publish-web

    - name: Publish Bundler Package
      run: make publish-bundler