name: Test & Publish

on: 
  release:
    types: # This configuration does not affect the page_build event above
      - prereleased
      - released

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true

    - uses: Swatinem/rust-cache@v1
      with:
          cache-on-failure: true

    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
        version: 'latest'
    - name: Run tests
      run: cargo test --verbose
    - name: Run WASM tests
      run: wasm-pack test --node

  node-test:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [14.x, 15.x]

      steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
          version: 'latest'

      - run: make build-nodejs
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn
        working-directory: examples/node-test
      - run: yarn test
        working-directory: examples/node-test
        
  publish:
    runs-on: ubuntu-latest
    needs: [test, node-test]

    steps:
    - uses: actions/checkout@v2
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
        version: 'latest'

    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true

    - uses: Swatinem/rust-cache@v1
      with:
          cache-on-failure: true
          
    - uses: katyo/publish-crates@v1
      with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

    - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

    - name: Publish Node Package
      run: make publish-node

    - name: Publish Web Package
      run: make publish-web

    - name: Publish Bundler Package
      run: make publish-bundler
