name: Test & Publish

on: 
  release:
    types: # This configuration does not affect the page_build event above
      - prereleased
      - released

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true

    - uses: Swatinem/rust-cache@v1
      with:
          cache-on-failure: true

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Install wasm-bindgen-cli Custom
      run: cargo install --git https://github.com/bsvwasm/wasm-bindgen --branch universal-ui64-patch wasm-bindgen-cli
      
    - name: Run tests
      run: cargo test --verbose
    - name: Run WASM tests
      run: make wasm-tests

  node-test:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [15.x, 16.x]

      steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Install wasm-opt
        run: apt-get install -y binaryen

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install wasm-bindgen-cli Custom
        run: cargo install --git https://github.com/bsvwasm/wasm-bindgen --branch universal-ui64-patch wasm-bindgen-cli

      - run: make build-nodejs
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn
        working-directory: examples/node-test
      - run: yarn test
        working-directory: examples/node-test
        
  publish:
    runs-on: ubuntu-latest
    needs: [test, node-test]

    steps:
    - uses: actions/checkout@v2

    - name: Install wasm-opt
      run: apt-get install -y binaryen
      
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Install wasm-bindgen-cli Custom
      run: cargo install --git https://github.com/bsvwasm/wasm-bindgen --branch universal-ui64-patch wasm-bindgen-cli

    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true

    - uses: Swatinem/rust-cache@v1
      with:
          cache-on-failure: true
          
    - uses: katyo/publish-crates@v1
      with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

    - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

    - name: Publish Node Package
      run: make publish-node

    - name: Publish Web Package
      run: make publish-web

    - name: Publish Bundler Package
      run: make publish-bundler
